version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: api.Dockerfile

  website:
    build:
      context: ./react_dashboard_app/
      dockerfile: website.Dockerfile
    ports:
      - "192.168.1.101:3001:3000"
