version: "3.9"
services:
  api:
    container_name: react-dashboard-api
    build:
      context: ./
      dockerfile: api.Dockerfile
    ports:
      - "4000:4000"

  website:
    container_name: react-dashboard-website
    build:
      context: ./react_dashboard_app/
      dockerfile: website.Dockerfile
    ports:
      - "192.168.1.101:3001:3000"
